version: '3'
services:
  redis:
      image: redis:latest
      container_name: rd01
      ports:
      - '6379:6379'
  db:
    image: "mysql"
    environment: 
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/foo
  smtp:
    image: "rnwood/smtp4dev"
    ports:
      - "2525:25"
      - "3000:80"


volumes:
  db-data: