# Generated by Django 4.1.7 on 2023-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cooperative',
            field=models.BooleanField(default=False),
        ),
    ]
