# Generated by Django 4.1.7 on 2023-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
