# Generated by Django 4.1.7 on 2023-05-27 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.product')),
            ],
        ),
    ]
